import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Clicks from '@/components/main/home/clicks';

export default function Home({ t }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="all" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Clicks />
    </>
  )
}

export async function getStaticProps({ locale }) {

  const rawt = await require(`@/locale/${locale ?? 'en'}`);

  const t = rawt.home;

  return {
    props: { t },
    revalidate: 60,
  };
}
